name: Discord Role Ping

# Run on any push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "<@&1486366928510386206> New commit pushed to main!"
